### ISSUE TITLE
onload event for map

### ISSUE THREAD

**Issue by jdillman1989** [manifestinteractive/jqvmap#128]
According to the documentation, this map API includes events for onLabelShow, onRegionOver, onRegionOut, and onRegionClick. Is there also an event included for when the map first renders? Or is there some simple way to target this event without it being included in the API? Would something like this work:

    jQuery('#vmap').onload('jqvmap'
        function(event, label, code)
        {
     
        }
    );

**Comment by manifestinteractive** [comment]
@jdillman1989 I have a test branch in place for this at:

https://github.com/manifestinteractive/jqvmap/tree/issue-128

You can now use either:

```js
var map = $('#vmap').vectorMap({
    map: 'world_en',
    onLoad: function(event, map){
      console.log(map);
    }
});
```
or 
```js
jQuery('#vmap').bind('load.jqvmap',
    function(event, map)
    {
      console.log(map);
    }
);
```

Please let me know if this works for you.  I have also added unit tests for this so we can merge it into master.  Since it's an old ticket ( sorry ), I will merge it automatically in the next few days if you are no longer able to test this.

**Comment by manifestinteractive** [comment]
You can now view PR #188
