### ISSUE TITLE
how to add outline to entire map area

### ISSUE THREAD

**Issue by jenlampton** [manifestinteractive/jqvmap#161]
Thanks for this amazing tool, I'm having a lot of fun with it!

I wonder, is there a way to add an outer-border (and/or drop-shadow) around the very border of the map region yet?  If not, I would like to add a feature request.

This screenshot is the map I am trying to create using jqvmap, the outer-border is the one in black.
![outer-border-arrows](https://cloud.githubusercontent.com/assets/397895/7506466/8b0647f2-f41d-11e4-99b6-8afbb5bb0de1.png)

**Comment by manifestinteractive** [comment]
I have no idea how to do this, anyone else want to chime in ?

**Comment by manifestinteractive** [comment]
@jenlampton So I looked into this, and I do not think it is possible.  The main issue is that each region ( in this case US State ) is its own shape in HTML's Canvas. While it is possible to add drop shadows and outlines to a Canvas Element ( e.g. http://www.html5canvastutorials.com/advanced/html5-canvas-shadow-offset-tutorial/ ) it would apply it to each region, not the outer part.

I actually tested this and the issue was that unless you could also create a shaped that was just the entire outline, there is no way to do it.  Since this library cannot do that ( and only creates and placed each region, rather than have a concept of the entire shape ) I will have to close this ticket since it's not possible.

If someone wants to tinker with the way the regions are drawn and clone the entire collection of regions and combine them as a new shape, then stack that new shape behind the collection of regions, that's one way you could apply a border and drop shadow ... but that is not something JQVMap does :(

**Comment by jenlampton** [comment]
Thanks for the answer :)
