### ISSUE TITLE
Documentation is a good start but is lacking

### ISSUE THREAD

**Issue by stormhillmedia** [manifestinteractive/jqvmap#172]
This package looks great but is a bit more work to implement that need be with some more documentation.

**Comment by huglester** [comment]
I just downloaded and went directly to /samples/ folder

**Comment by manifestinteractive** [comment]
@stormhillmedia a few questions for you:

1.  What were you looking for that you did not find ?
2.  What was more work than you expected ?
3.  Anything specific you can think of other than just saying we need "more documentation" ?

I ask because every method is fully documented, and there is a sample folder showing multiple implementations.  I would love to help make this easier for people, but I am not entirely sure where you got stuck since you did not provide that information.

See, documentation is not as easy as we would all like ;)

**Comment by manifestinteractive** [comment]
Closing issue.  If there are specific things lacking in documentation, let's create a new issue listing what specifically is missing so we can tackle them in a more organized fashion.
