### ISSUE TITLE
Problems with 1.4.0 in Firefox (Iceweasel) and Qupzilla

### ISSUE THREAD

**Issue by andreasspeck** [manifestinteractive/jqvmap#196]
When I try to update jqvmap from 1.3.1 to 1.4.0, this works fine in Chrome, but in Firefox (Iceweasel from Debian Sid) and Qupzilla it does not display the map, but I also do not see any message. I seem to get message caused by another script (or by Joomla - I'm doing this in an Joomla component) that Javascript needs to be enabled - which seems to be caused by the update. Downgrading to 1.3.1 again and emptying browser cache gets it to work again.

**Comment by manifestinteractive** [comment]
@andreasspeck I have tested this in the default FireFox browser for both OSX & Windows without any issues.  I personally am only testing mainstream browsers for this project, so if you end up finding the issue, please let me know ( or submit a PR if you find a fix ).

**Comment by manifestinteractive** [comment]
Just a heads up that I am closing this ticket, only because it is for a browser that is not supported.  Had this been an official FireFox release that was broken I'd be happy to work on this.  Previously I had left tickets open on the off chance someone could pick it up... but once our ticket count got to 100+ things just got unmanageable for pretty much anyone.
