### ISSUE TITLE
What my Map is Not Working in New Firefox Browsers

### ISSUE THREAD

**Issue by mahmoud-eskandari** [manifestinteractive/jqvmap#200]
https://github.com/manifestinteractive/jqvmap/blob/master/examples/iran.html

This Example Working Good in chrome But not working correct  in Firefox!
I check All JavaScript Parameters,But I don't fix it For Firefox.

Can you Check it?
Thank's

**Comment by sureshopensoft** [comment]
I am also have same issue, Kindly provide any suggestion to fix this issue

**Comment by manifestinteractive** [comment]
This seems to be a specific issue with only that map file and not JQVMap itself.  If someone would like to recreate this map they can do so using the https://github.com/manifestinteractive/jqvmap/tree/master/create toolset

**Comment by manifestinteractive** [comment]
BTW, The contact info for the map creator is located in the map file

**Comment by manifestinteractive** [comment]
Unfortunately, I do not create the map files, otherwise I would try to help out.  I only maintain the software that loads the libraries.  The Map Creator was open source software created by someone else in a language I am not at all familiar with... so sadly, this project does not really manage the maps other people submit.  We just do our best to make sure they work for everyone.  If this one does not, we can either have the author fix it, or have someone in the community give it a go.

It's been three months with this ticket open, and unfortunately I have to do some house cleaning on the project.  Since we can easily solve this with a Pull Request, I will look forward to seeing that come in and we can revisit this issue at that time.
