### ISSUE TITLE
Text align issue for states

### ISSUE THREAD

**Issue by tmuks** [manifestinteractive/jqvmap#231]
Texts are not aligned centered to map, also position relative is not working, with other element on screem, all text are displayed at different position instead where they should be 

![jqvmap issue](https://cloud.githubusercontent.com/assets/8498097/15279604/c5fcf4e8-1b43-11e6-9057-387c4517be57.PNG)

**Comment by manifestinteractive** [comment]
You will likely need to recreate your entire issue online for us to review.  Currently we have a `labels.html` file that works perfectly.  It is likely something you have in your CSS that is causing some issues.  Usually this kind of stuff is usually some global overrides in CSS that are causing issues.

https://github.com/manifestinteractive/jqvmap/blob/master/examples/labels.html

I have attached a screenshot of it below:

<img width="1380" alt="screen shot 2016-05-17 at 6 46 34 pm" src="https://cloud.githubusercontent.com/assets/508411/15341969/e9a6a2f0-1c5f-11e6-982a-0f24b482899f.png">

I will leave this issue open for others to help out ( if you create a working example some place online ).  But since the labels do work in all major browsers using the tested file, there is little more I can do to help.

**Comment by tmuks** [comment]
Tx for reply.
Here is link to view the issue online: http://119.18.49.90/~mukundto/vmap/
It seems dimension calculation issue and position of vmap

Try to add some hidden element before the map in default map you will see this behaviour

**Comment by manifestinteractive** [comment]
Just as I thought, the issue is CSS related.

You can remove `position: relative;` from both your inline CSS as well as the `#vmap` element.

Get's things looking about normal.  You will still need to add custom stylings for the states that aren't quote centered.  But here is your own example with the irrelevant CSS stylings:

![screen shot 2016-05-17 at 10 20 17 pm](https://cloud.githubusercontent.com/assets/508411/15345506/add00ba4-1c7d-11e6-80be-6acc356e1a79.png)

That included CSS file is just for reference, obviously once you put the site on your page, you are able to control the styling however you want :)

**Comment by tmuks** [comment]
Tx. It worked
Inline css were applied from jquery.vmap.js, removed that and working fine.
