### ISSUE TITLE
Sync the version info in files with tagged version

### ISSUE THREAD

**Issue by pvnr0082t** [manifestinteractive/jqvmap#234]
Hi @manifestinteractive ,
In the v1.5.1 release, I found that version information in `jquery.vmap.js` and `jquery.vmap.min.js` are still v1.5.0. Could you please sync these version infos with release version? Thanks a lot.

https://github.com/cdnjs/cdnjs/pull/7928
https://github.com/cdnjs/cdnjs/issues/7716

**Comment by manifestinteractive** [comment]
Updated Release v1.5.1.  Forgot to do a new build since there were no JS changes.  New build has correct version :)

**Comment by pvnr0082t** [comment]
Okay, thanks for your help. :+1: 
Btw, it'll be good to update release v1.5.1 on npm. :)

**Comment by manifestinteractive** [comment]
I had already run `npm publish`  on version 1.5.1 ( with the wrong version in comment ).  Without updating to a new version I was not sure how to republish the package without creating a whole new version.  I can do what if it makes sense.  Just seemed weird to create a whole new version because of a comment.  If there is a way to update the npm package and maintain the same version number, let me know :)
