### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by limitedgoods** [manifestinteractive/jqvmap#236]
Can you add the ability to have more than 1 pin per state. I may be wrong but from what i can tell each state (USA) can only have 1 pin per. thanks.

**Comment by manifestinteractive** [comment]
You can set both Pins and Labels as HTML ... so technical you can make whatever you want be a pin ... including custom HTML CSS that makes it look like more pins.

The issue with supporting multiple pins is there is no way to place them other than in direct center.  Even if we added some custom logic to offset these pins, there is no way to control where each one goes if the user wanted more control.

The best option is something we already support ... which is just to use HTML for your pins or labels, and just style them using CSS.  

Example:

```js
jQuery('#vmap').vectorMap(
{
    onLabelShow: function(event, label, code)
    {
        // HTML Based Labels. You can use any HTML you want, this is just an example
        label.html('<div class="pins-wrapper"><div class="my-pin pin-1"></div><div class="my-pin pin-2"></div><div class="my-pin pin-3"></div></div>');
    }
});
```

This will put HTML where you labels are and you can use javascript plus the `label` & `code` parameters to pretty much do whatever you want.  Then you can add CSS to style the pins since they have class names... even positioning them wherever you want from the center positioning they will have.
