### ISSUE TITLE
France Map

### ISSUE THREAD

**Issue by nmallepally** [manifestinteractive/jqvmap#237]
![france map](https://cloud.githubusercontent.com/assets/19605497/15678676/21475ad2-2747-11e6-8a6c-4541c9af4008.png)
Hello,

I found out that we are using your map on our website and i want to change the names for zones highlighted in the image. here is the url of map on website ([http://www.tricel.fr/partenaires](url)

According to image attached zone circled as red is calling one name, but i need each of them circled in black as different names. the blue color zone should be AlpesNord and yellow should be AlpesNordLoire. but at present the ones in yellow and blue in red marked zone are called from AlpesNordLoire only. I want to have blue one in AlpesNord and different name, for which i need co-ordinates to seprate it out.
Can you help me with this. I need the vector codes for AlpesNord .. Im attaching the source file as well.
what is the link with raphael map ??
[Uploading jvf.txt…]()

Thanks.

**Comment by manifestinteractive** [comment]
@nmallepally this seems like you are just needing help with development of your custom website, not help with a bug in JQVMap.  I am closing this ticket since it is not actually an issue or feature request ... and really not even a question about features.  This just seems like you are asking for someone to tell you how to use already documented features.

If you had any specific questions about how to use the documented features that maybe you are stuck on, please followup here and I will reopen the issue.  But please note what we can only help you if you actually can show you tried to do this yourself and had no success ... and even then, we would need to see an example of what you did, what you were expecting to happen, and what is not actually working for you.
