### ISSUE TITLE
Missing countries

### ISSUE THREAD

**Issue by githeko** [manifestinteractive/jqvmap#244]
Hi;

Thanks so much for the "world_en" SVG map. I am using it to construct an open app and discovered that **South Sudan** and **Singapore** are missing. There could be other nations since I did not go through the complete ccTLD list. If there is any way I can help with the project, I would be happy to chip in.

Jason M. Githeko

**Comment by acz13** [comment]
https://github.com/manifestinteractive/jqvmap/tree/master/create

**Comment by manifestinteractive** [comment]
As @acz13 mentioned, there is a way to create your own maps if the ones that are provided are not to your liking.  The issue with map creations is that it is pretty much impossible to get all the countries in the map because of the software that is used ( which was not created by us ).

If someone wants to take a crack at this, go for it ... but it's literally never been possible in the duration of this projects history, and certainly something I ( the main author & maintainer ) can figure out... which is why I am closing this ticket as something we will not attempt to fix.

It's just not something anyone has figured out.
