### ISSUE TITLE
Can I use jqvmap in commerical project?

### ISSUE THREAD

**Issue by forethoughtde** [manifestinteractive/jqvmap#309]
Hello @manifestinteractive, 

I like to know if I can use the project in commercial project? Can you please let me know?

Thanks in advance, 

Regards,

Karthikeyan

**Comment by manifestinteractive** [comment]
Our [LICENSE](https://github.com/manifestinteractive/jqvmap/blob/master/LICENSE) is MIT & GPL and covers what your are allowed to do with this software.

Short Answer:  Yes, as long as you include our original LICENSE with the software you release commercially, as required by the LICENSE agreement.

**Comment by forethoughtde** [comment]
Does the project have any connection with jVectorMap? Because JVectorMap have some restrictions on commercial use. I am asking you this because you have added in the README.md file that it is heavily modified version of jVectorMap.

**Comment by manifestinteractive** [comment]
JQVMap has been completely rewritten since [v1.3.0](https://github.com/manifestinteractive/jqvmap/releases/tag/v1.3.0) ( released on December 4th, 2015 ). We have had unique contributions from others under the MIT & GPL license.  Our intentions are still keep our map files compatible with the `JVectorMap` project, as their is no reason for us to not try to support that project with our Map Files, if we can.

Technically every since v1.1.0 our project has taken a MAJOR directional change code wise from `JVectorMap` and the original v1.0.0 of our project is not even maintained here as an official release since it contained about 35% of the original `JVectorMap` code from one of the releases back in 2012 or 2013.

Hopefully that answers your question.  I leave the bit about `JVectorMap` in the README to show respect for the origins of this project since that is where it started over 5 years ago ( original commit was May 5, 2012 ).

**Comment by jimasp** [comment]
I think whether you want to use GNU GPL software in a commercial product depends on whether you are happy that anyone can request the full source code of your product (you are legally obliged by the license to do this).

The JQVMap license file states:
"This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version."

The GNU GPL License states:

"...if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. **You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights.**"

"You may convey a work based on the Program... provided that you also meet all of these conditions:
...c) **You must license the entire work, as a whole, under this License** to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the **whole of the work, and all its parts, regardless of how they are packaged**. This License gives no permission to license the work in any other way"

"Corresponding Source conveyed... in accord with this section must be in a format that is publicly documented (and with an implementation available to the public in source code form)"
