### ISSUE TITLE
Map errors

### ISSUE THREAD

**Issue by Janhouse** [manifestinteractive/jqvmap#37]
Sorry, but Latvia doesn't  look like that on map.
The shape in the world map is wrong (but seems ok in Europe view).

https://en.wikipedia.org/wiki/Latvia

**Comment by Janhouse** [comment]
@manifestinteractive, WTF? You could just fix it in your fork.  :-1: 
Thanks @bjornd!

**Comment by manifestinteractive** [comment]
Map files are created by individuals using a third party python script ( instructions provided in both mentioned map projects ). If you are not satisfied with the way a map was generated by that script, you are welcome to correct it and submit your own PR.  Both JQVMap or jvectormap focus on displaying the maps generated by the third party tool, no custom creating maps for people.

Demanding someone fix something for you is not how open source projects work.  You are welcome to use any other library that better suits your needs, e.g. http://jvectormap.com which is owned by @bjornd whom you thanked.

Better would be to work on fixing the map to be correct, since you apparently know what it SHOULD look like and no one else in three years cared to address this publicly available issue.  In fact, having the ticket open for three years without it being picked up is why it was closed.

Again, if you care to submit a pull request with the fix you want in place, I will be more than happy to include it.  But neither this project, or jvectormap are in the business of custom making maps for people.  But should theirs have a better map, you are welcome to use it :)
